# Generated by Django 3.2.7 on 2021-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycafe',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gallerycafe',
            name='image4',
            field=models.ImageField(null=True, upload_to='main/'),
        ),
        migrations.AddField(
            model_name='gallerycafe',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gallerycafe',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gallerycafe',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gallerycafe',
            name='image2',
            field=models.ImageField(null=True, upload_to='main/'),
        ),
        migrations.AlterField(
            model_name='gallerycafe',
            name='image3',
            field=models.ImageField(null=True, upload_to='main/'),
        ),
    ]
